import { INodePropertyOptions } from 'n8n-workflow';

export const Static_Country_Proxies: INodePropertyOptions[] = [
	{ name: 'Afghanistan', value: 'Afghanistan' },
	{ name: 'Albania', value: 'Albania' },
	{ name: 'Algeria', value: 'Algeria' },
	{ name: 'Argentina', value: 'Argentina' },
	{ name: 'Armenia', value: 'Armenia' },
	{ name: 'Aruba', value: 'Aruba' },
	{ name: 'Australia', value: 'Australia' },
	{ name: 'Austria', value: 'Austria' },
	{ name: 'Azerbaijan', value: 'Azerbaijan' },
	{ name: 'Bahamas', value: 'Bahamas' },
	{ name: 'Bahrain', value: 'Bahrain' },
	{ name: 'Bangladesh', value: 'Bangladesh' },
	{ name: 'Belarus', value: 'Belarus' },
	{ name: 'Belgium', value: 'Belgium' },
	{ name: 'Bosnia and Herzegovina', value: 'Bosnia and Herzegovina' },
	{ name: 'Brazil', value: 'Brazil' },
	{ name: 'British Virgin Islands', value: 'British Virgin Islands' },
	{ name: 'Brunei', value: 'Brunei' },
	{ name: 'Bulgaria', value: 'Bulgaria' },
	{ name: 'Cambodia', value: 'Cambodia' },
	{ name: 'Cameroon', value: 'Cameroon' },
	{ name: 'Canada', value: 'Canada' },
	{ name: 'Chile', value: 'Chile' },
	{ name: 'China', value: 'China' },
	{ name: 'Colombia', value: 'Colombia' },
	{ name: 'Costa Rica', value: 'Costa Rica' },
	{ name: 'Croatia', value: 'Croatia' },
	{ name: 'Cuba', value: 'Cuba' },
	{ name: 'Cyprus', value: 'Cyprus' },
	{ name: 'Czechia', value: 'Czechia' },
	{ name: 'Denmark', value: 'Denmark' },
	{ name: 'Dominican Republic', value: 'Dominican Republic' },
	{ name: 'Ecuador', value: 'Ecuador' },
	{ name: 'Egypt', value: 'Egypt' },
	{ name: 'El Salvador', value: 'El Salvador' },
	{ name: 'Estonia', value: 'Estonia' },
	{ name: 'Ethiopia', value: 'Ethiopia' },
	{ name: 'Finland', value: 'Finland' },
	{ name: 'France', value: 'France' },
	{ name: 'Georgia', value: 'Georgia' },
	{ name: 'Germany', value: 'Germany' },
	{ name: 'Ghana', value: 'Ghana' },
	{ name: 'Greece', value: 'Greece' },
	{ name: 'Guatemala', value: 'Guatemala' },
	{ name: 'Guyana', value: 'Guyana' },
	{ name: 'Hashemite Kingdom of Jordan', value: 'Hashemite Kingdom of Jordan' },
	{ name: 'Hong Kong', value: 'Hong Kong' },
	{ name: 'Hungary', value: 'Hungary' },
	{ name: 'India', value: 'India' },
	{ name: 'Indonesia', value: 'Indonesia' },
	{ name: 'Iran', value: 'Iran' },
	{ name: 'Iraq', value: 'Iraq' },
	{ name: 'Ireland', value: 'Ireland' },
	{ name: 'Israel', value: 'Israel' },
	{ name: 'Italy', value: 'Italy' },
	{ name: 'Jamaica', value: 'Jamaica' },
	{ name: 'Japan', value: 'Japan' },
	{ name: 'Kazakhstan', value: 'Kazakhstan' },
	{ name: 'Kenya', value: 'Kenya' },
	{ name: 'Kosovo', value: 'Kosovo' },
	{ name: 'Kuwait', value: 'Kuwait' },
	{ name: 'Latvia', value: 'Latvia' },
	{ name: 'Liechtenstein', value: 'Liechtenstein' },
	{ name: 'Luxembourg', value: 'Luxembourg' },
	{ name: 'Macedonia', value: 'Macedonia' },
	{ name: 'Madagascar', value: 'Madagascar' },
	{ name: 'Malaysia', value: 'Malaysia' },
	{ name: 'Mauritius', value: 'Mauritius' },
	{ name: 'Mexico', value: 'Mexico' },
	{ name: 'Mongolia', value: 'Mongolia' },
	{ name: 'Montenegro', value: 'Montenegro' },
	{ name: 'Morocco', value: 'Morocco' },
	{ name: 'Mozambique', value: 'Mozambique' },
	{ name: 'Myanmar', value: 'Myanmar' },
	{ name: 'Nepal', value: 'Nepal' },
	{ name: 'Netherlands', value: 'Netherlands' },
	{ name: 'New Zealand', value: 'New Zealand' },
	{ name: 'Nigeria', value: 'Nigeria' },
	{ name: 'Norway', value: 'Norway' },
	{ name: 'Oman', value: 'Oman' },
	{ name: 'Pakistan', value: 'Pakistan' },
	{ name: 'Palestine', value: 'Palestine' },
	{ name: 'Panama', value: 'Panama' },
	{ name: 'Papua New Guinea', value: 'Papua New Guinea' },
	{ name: 'Paraguay', value: 'Paraguay' },
	{ name: 'Peru', value: 'Peru' },
	{ name: 'Philippines', value: 'Philippines' },
	{ name: 'Poland', value: 'Poland' },
	{ name: 'Portugal', value: 'Portugal' },
	{ name: 'Puerto Rico', value: 'Puerto Rico' },
	{ name: 'Qatar', value: 'Qatar' },
	{ name: 'Republic of Lithuania', value: 'Republic of Lithuania' },
	{ name: 'Republic of Moldova', value: 'Republic of Moldova' },
	{ name: 'Romania', value: 'Romania' },
	{ name: 'Russia', value: 'Russia' },
	{ name: 'Saudi Arabia', value: 'Saudi Arabia' },
	{ name: 'Senegal', value: 'Senegal' },
	{ name: 'Serbia', value: 'Serbia' },
	{ name: 'Seychelles', value: 'Seychelles' },
	{ name: 'Singapore', value: 'Singapore' },
	{ name: 'Slovakia', value: 'Slovakia' },
	{ name: 'Slovenia', value: 'Slovenia' },
	{ name: 'Somalia', value: 'Somalia' },
	{ name: 'South Africa', value: 'South Africa' },
	{ name: 'South Korea', value: 'South Korea' },
	{ name: 'Spain', value: 'Spain' },
	{ name: 'Sri Lanka', value: 'Sri Lanka' },
	{ name: 'Sudan', value: 'Sudan' },
	{ name: 'Suriname', value: 'Suriname' },
	{ name: 'Sweden', value: 'Sweden' },
	{ name: 'Switzerland', value: 'Switzerland' },
	{ name: 'Syria', value: 'Syria' },
	{ name: 'Taiwan', value: 'Taiwan' },
	{ name: 'Tajikistan', value: 'Tajikistan' },
	{ name: 'Thailand', value: 'Thailand' },
	{ name: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
	{ name: 'Tunisia', value: 'Tunisia' },
	{ name: 'Turkey', value: 'Turkey' },
	{ name: 'Uganda', value: 'Uganda' },
	{ name: 'Ukraine', value: 'Ukraine' },
	{ name: 'United Arab Emirates', value: 'United Arab Emirates' },
	{ name: 'United Kingdom', value: 'United Kingdom' },
	{ name: 'United States', value: 'United States' },
	{ name: 'Uzbekistan', value: 'Uzbekistan' },
	{ name: 'Venezuela', value: 'Venezuela' },
	{ name: 'Vietnam', value: 'Vietnam' },
	{ name: 'Zambia', value: 'Zambia' },
];
